name: Deploy static content to Pages

on:
  push:
    branches:
      - "main"
      - "test_build"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Move test build files into /test folder
      - name: Move test build to /test folder
        if: github.ref_name == 'test_build'
        run: |
          mkdir -p test/Build test/StreamingAssets test/TemplateData
          mv -f Build/* test/Build/
          mv -f StreamingAssets/* test/StreamingAssets/
          mv -f TemplateData/* test/TemplateData/
          mv index.html test/

      # Debug step: List directory contents
      - name: List directory contents
        run: ls -R .

      # Upload production artifact for main branch
      - name: Upload production artifact
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # Upload test artifact for test_build branch
      - name: Upload test artifact
        if: github.ref_name == 'test_build'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'test'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

